api_key: ""
max_retries: 10
timeout: 1
safety_settings:
  HARM_CATEGORY_HATE_SPEECH: BLOCK_NONE
  HARM_CATEGORY_HARASSMENT: BLOCK_NONE
  HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_NONE
  HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_NONE