api_key: "AIzaSyDIWrOab1dhFGh8S1Tf8ft-1E5ex2qJSZw"
max_retries: 10
timeout: 1
safety_settings:
  HARM_CATEGORY_HATE_SPEECH: BLOCK_NONE
  HARM_CATEGORY_HARASSMENT: BLOCK_NONE
  HARM_CATEGORY_SEXUALLY_EXPLICIT: BLOCK_NONE
  HARM_CATEGORY_DANGEROUS_CONTENT: BLOCK_NONE