dataset_id: "instruction-logic"
model_id: "llava-v1.5-7b"

log_file: "./logs/truthfulness/instruction-enhancement-logic.json"

evaluator_seq_cfgs:
  [
    {
      "chatmodel_eval":
        { 
          model_id: 'qwen-vl-chat',
          prompt_template: "Here is a response:{pred}, its ground truth:{label}. Please directly answer [Yes] or [No] by judging whether the response of question is consistent with [Correct Answer] in its ground truth. Don't return your analysis process!",
          generation_kwargs: {
              'max_new_tokens': 100,
              'do_sample': False,
          },
          metrics_cfg: {}
        },
      "rule_yes_or_no_eval":
        {  
          metrics_cfg: { pred_mean: {} }
        }
    }
  ]
